### PR TITLE
Fix anonymous authentication with empty trace information string

### LINKED ISSUE #258: Client anonymous authentication not working when sending empty trace string
Example code:
```
client.Auth(sasl.NewAnonymousClient(""))
```

Output from a test server:
```
220 localhost ESMTP Service Ready
EHLO localhost
250-Hello localhost
250-PIPELINING
250-8BITMIME
250-ENHANCEDSTATUSCODES
250-CHUNKING
250-AUTH ANONYMOUS
250-SIZE 1024
250 LIMITS RCPTMAX=10
AUTH ANONYMOUS
334
*
501 5.0.0 Negotiation cancelled
smtp/server 2024/04/10 19:25:09 handler error: read tcp 127.0.0.1:10025->127.0.0.1:58986: wsarecv: An existing connection was forcibly closed by the remote host.
```

Output from a test client:

```
220 localhost ESMTP Service Ready
EHLO localhost
250-Hello localhost
250-PIPELINING
250-8BITMIME
250-ENHANCEDSTATUSCODES
250-CHUNKING
250-AUTH ANONYMOUS
250-SIZE 1024
250 LIMITS RCPTMAX=10
AUTH ANONYMOUS
334
*
501 5.0.0 Negotiation cancelled
2024/04/10 19:25:09 sasl: unexpected server challenge
```

### PR DESCRIPTION
**Pull request by albertony**
With anonymous authentication according to RFC4505 the trace information string is optional, and SMTP authentication extension described in RFC4954 states that:

    If the client is transmitting an initial response of zero
    length, it MUST instead transmit the response as a single
    equals sign ("=").  This indicates that the response is
    present, but contains no data.

Fixes #258

### CODE REVIEW

**Comment by emersion** [comment]
These changes look good to me overall, just one comment: I think we probably need to also handle `=` when sent as a regular response (not an initial response)? See the other `base64.StdEncoding.DecodeString` call done below in the same function, inside the `for` loop.

**Comment by albertony** [comment]
I agree. Force pushed an update. I tested it with openssl s_client against my go-smtp based test server, and I assume a sequence like this is what you were thinking of:

```
EHLO localhost
250-Hello localhost
250-PIPELINING
250-8BITMIME
250-ENHANCEDSTATUSCODES
250-CHUNKING
250-AUTH ANONYMOUS
250-SIZE 1024
250 LIMITS RCPTMAX=10
AUTH ANONYMOUS
334
=
```

PTAL

File: client.go [hunk 1]
```diff
@@ -356,8 +356,13 @@ func (c *Client) Auth(a sasl.Client) error {
 	if err != nil {
 		return err
 	}
-	resp64 := make([]byte, encoding.EncodedLen(len(resp)))
-	encoding.Encode(resp64, resp)
+	var resp64 []byte
+	if len(resp) > 0 {
+		resp64 = make([]byte, encoding.EncodedLen(len(resp)))
+		encoding.Encode(resp64, resp)
+	} else {
```
Comment (emersion) [inline client.go:363]: Oh, one last thing: the go-sasl API has the same nil vs empty slice footgun in the `Client` interface. Namely, here `resp = nil` means no initial response, while `resp = []byte{}` means an empty initial response.

The fix would be to replace this line with `} else if resp != nil {` I believe.

Comment (albertony) [reply client.go:363]: Hm, ok. Force pushed update. I haven't tested it though, wasn't immediately sure how to (and no time to investigate more right now).

Comment (emersion) [reply client.go:363]: That's OK. Would need to find a SASL mechanism with no initial response, I don't know of any.

It seems like the push hasn't gone through?

Comment (albertony) [reply client.go]: Ah, sorry. Forgot the commit in between add and push... 🥵

Comment (albertony) [reply client.go]: Was that change what you intended?

**Review by emersion — APPROVED** [review]
LGTM, thank you!

**Comment by emersion** [comment]
Oh, CI is unhappy now… Maybe the test actually tests the no initial response case, as opposed to the empty initial response one?

**Comment by emersion** [comment]
Seems like it:

```go
func (toServerEmptyAuth) Start() (proto string, toServer []byte, err error) {
	return "FOOAUTH", nil, nil
}
```

**Comment by emersion** [comment]
I've removed the test changes, and fixed up the outdated comments in 029f7513c5fe.

**Comment by albertony** [comment]
Ahhh, real sorry about that! I've been running that many times, and adjusted it in a previous iteration, but probably forgot about it during these last iterations. Thanks for fixing it (I'm not at computer right now anyway).

**Comment by emersion** [comment]
Yeah, no worries whatsoever, it's been a ride untangling this mess!
